# Generated by Django 5.2.8 on 2025-12-08 09:17

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('budget', '0002_financialhealthscore_loanapplication_loanrepayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomaticBillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_msisdn', models.CharField(help_text='Recipient EcoCash number (263XXXXXXXXX)', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('reason', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('next_payment_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_payments', to='budget.budgetcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_bill_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auto_bill_payments',
                'ordering': ['next_payment_date'],
            },
        ),
        migrations.CreateModel(
            name='EcoCashPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_msisdn', models.CharField(max_length=15)),
                ('recipient_msisdn', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('ecocash_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('auto_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='ecocash.automaticbillpayment')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecocash_payment', to='accounting.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecocash_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ecocash_payments',
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='ecocash_pay_user_id_2771d1_idx'), models.Index(fields=['source_reference'], name='ecocash_pay_source__3b9857_idx')],
            },
        ),
    ]
