# Generated by Django 5.2.8 on 2025-12-09 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecocash', '0002_ecocash_api_integration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecocashpayment',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='ecocashpayment',
            name='reference',
        ),
    ]
