# Generated by Django 5.2.8 on 2025-12-08 10:20

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transfer_type', models.CharField(choices=[('send_to_registered', 'Send to Registered User'), ('send_to_unregistered', 'Send to Unregistered User'), ('send_to_account', 'Send to Account'), ('usd_to_zig', 'USD to Zig')], max_length=20)),
                ('recipient_phone', models.CharField(blank=True, max_length=15)),
                ('recipient_account', models.CharField(blank=True, max_length=50)),
                ('recipient_name', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency_from', models.CharField(default='USD', max_length=3)),
                ('currency_to', models.CharField(default='USD', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10)),
                ('amount_received', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer', to='accounting.transaction')),
            ],
            options={
                'db_table': 'transfers',
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['sender', 'status'], name='transfers_sender__da98ff_idx'), models.Index(fields=['reference'], name='transfers_referen_ad0d1d_idx')],
            },
        ),
    ]
